spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smallworlds
    username: smallworlds
    password: smallworlds123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080